### ISSUE TITLE
Could not authenticate you

### ISSUE THREAD

**Issue by talha2k** [CodyBontecou/day-1-tweet-with-nodejs#1]
Followed all steps and getting following error:

[ { code: 32, message: 'Could not authenticate you.' } ]

**Comment by CodyBontecou** [comment]
Hey, @talha2k, do you have a reproduction repo I can look at? 
I know Twitter is going through many changes, and their API is probably unreliable.

**Comment by talha2k** [comment]
Hey hey. I was able to solve it by regenerated tokens and keys few times.

**Comment by CodyBontecou** [comment]
Awesome, I'm glad that worked out!
